### ISSUE TITLE
Error From Flutter client

### ISSUE THREAD

**Issue by gregoryvanhout** [invoiceninja/flutter-client#217]
main.dart.js,qv=5.1.27.pagespeed.ce.Ht1qyDsi7R.js:66731 Uncaught PlatformException(Unregistered factory, No factory registered for viewtype 'null', null, null)
    at Object.e (https://finance.gregit.help/main.dart.js,qv=5.1.27.pagespeed.ce.Ht1qyDsi7R.js:3354:3)
    at bEU.TY (https://finance.gregit.help/main.dart.js,qv=5.1.27.pagespeed.ce.Ht1qyDsi7R.js:105872:14)
    at https://finance.gregit.help/main.dart.js,qv=5.1.27.pagespeed.ce.Ht1qyDsi7R.js:105918:98
    at cKi.a (https://finance.gregit.help/main.dart.js,qv=5.1.27.pagespeed.ce.Ht1qyDsi7R.js:4915:71)
    at cKi.$2 (https://finance.gregit.help/main.dart.js,qv=5.1.27.pagespeed.ce.Ht1qyDsi7R.js:65475:23)
    at cr2.$1 (https://finance.gregit.help/main.dart.js,qv=5.1.27.pagespeed.ce.Ht1qyDsi7R.js:65467:30)
    at aLY.v6 (https://finance.gregit.help/main.dart.js,qv=5.1.27.pagespeed.ce.Ht1qyDsi7R.js:66776:42)
    at c3_.$0 (https://finance.gregit.help/main.dart.js,qv=5.1.27.pagespeed.ce.Ht1qyDsi7R.js:65965:11)
    at Object.a_n (https://finance.gregit.help/main.dart.js,qv=5.1.27.pagespeed.ce.Ht1qyDsi7R.js:5040:40)
    at aF.tL (https://finance.gregit.help/main.dart.js,qv=5.1.27.pagespeed.ce.Ht1qyDsi7R.js:65870:3)

**Comment by hillelcoren** [comment]
Hi,

We'll look into it but I think it can be safely ignored.

**Comment by gregoryvanhout** [comment]
Dear, 

The problem is that is is not generating pdf anymore sinds that error

Kind Regards

**Comment by hillelcoren** [comment]
It looks like you've created a separate issue with a different error? 

https://github.com/invoiceninja/invoiceninja/issues/5181
